### ISSUE TITLE
报错：ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by pooneyy** [Plutoeat/sign_in_jrxy#2]
![image](https://user-images.githubusercontent.com/85266337/151114441-aa55bc0f-671d-4c43-a545-a364024831cf.png)
报错：ModuleNotFoundError: No module named 'Crypto'，但是事实上已经安装了

**Comment by Plutoeat** [comment]
这种一般是包名的问题，你可以直接去site-package文件夹下把小写的c改为大写，找不到你就在我代码的引用中将大写改为小写，一般crypto出问题都是这个原因

**Comment by Plutoeat** [comment]
我不怎么上github，你可以直接发我邮件，新代码已经发布可以通知结果，你可以直接下新代码，这个项目我应该是不怎么更新了，搞这个费的时间还不如老实签到，我另一篇文档，参考文献那个第三个大佬，他的项目还能用，支持更广，使用也相对复炸些

**Comment by Plutoeat** [comment]
我不怎么上github，你可以直接发我邮件，新代码已经发布可以通知结果，你可以直接下新代码，这个项目我应该是不怎么更新了，搞这个费的时间还不如老实签到，我另一篇文档，参考文献那个第三个大佬，他的项目还能用，支持更广，使用也相对复炸些
