### ISSUE TITLE
阿里云函数执行失败，是为什么呀

### ISSUE THREAD

**Issue by pooneyy** [Plutoeat/sign_in_jrxy#3]
![image](https://user-images.githubusercontent.com/85266337/151131720-8bc329ed-9cbd-4ef1-aeb3-9ee7246933a2.png)
返回结果：{"errorMessage":"Process exited unexpectedly before completing request (duration: 3023ms, maxMemoryUsage: 74MB)"}
日志：
FunctionCompute python3 runtime inited.
FC Invoke Start RequestId: adb9ea5a-03f4-4f2d-9f88-0e9cd245f176
FC Invoke End RequestId: adb9ea5a-03f4-4f2d-9f88-0e9cd245f176, Error: Process exited unexpectedly before completing request (duration: 3023ms, maxMemoryUsage: 74MB)

**Comment by Plutoeat** [comment]
你收到server酱通知了吗？

**Comment by Plutoeat** [comment]
我看一下你函数配置

**Comment by Plutoeat** [comment]
这种一般是你生命周期设断了，代码我已经针对阿里云函数改过了了，你把生命周期设置到1000到1500

**Comment by pooneyy** [comment]
![image](https://user-images.githubusercontent.com/85266337/151149433-423c351d-8d70-40f7-b602-300fd567dcee.png)
这是我的函数配置。不知道您的邮箱，可否留一下？

**Comment by Plutoeat** [comment]
index.py文件里有，你执行时间短了，按我说的1500左右，然后新代码一定配置文件加两行swnd-msg,和sendkey，具体不知道变了哪些就用新代码的generate.py重新生成个配置文件
